loan_delinquency_command_center:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: dbt_warehouse.duckdb
      threads: 4
    snowflake:
      type: snowflake
      account: nwzinzy-bs92383
      user: BOSEADITYA1994
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: LOAN_DELINQUENCY_CC_DBT
      schema: dbt_default
      threads: 4
